from app.models.scaffold_models import SprintExecutionRequest
from app.services.scaffold_service import generate_file_for_ticket
from app.services.git_service import push_files_to_repo

import os
import subprocess
import tempfile
import shutil
import json
import datetime


# -----------------------------------------
# Repo Utilities
# -----------------------------------------

def file_exists_in_repo(repo_url: str, branch_name: str, file_path: str) -> bool:
    temp_dir = tempfile.mkdtemp()

    try:
        subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", branch_name, repo_url, "."],
            cwd=temp_dir,
            capture_output=True
        )

        return os.path.exists(os.path.join(temp_dir, file_path))

    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)


def read_existing_repo_files(repo_url: str, branch_name: str) -> dict:
    """
    Clone repo and read all existing files.
    Returns { "relative/path/file.py": "file content" }
    Used to feed AST context into scaffold_service.
    """
    temp_dir = tempfile.mkdtemp()
    existing_files = {}

    try:
        result = subprocess.run(
            ["git", "clone", "--depth", "1", "--branch", branch_name, repo_url, "."],
            cwd=temp_dir,
            capture_output=True,
            text=True
        )

        if result.returncode != 0:
            print(f"[read_existing_repo_files] Clone failed: {result.stderr}")
            return {}

        for root, dirs, files in os.walk(temp_dir):
            dirs[:] = [
                d for d in dirs
                if not d.startswith(".")
                and d not in ("__pycache__", "node_modules", "venv", ".venv")
            ]

            for file in files:
                if file.endswith((".py", ".json", ".yaml", ".yml", ".ts", ".tsx", ".js", ".jsx")):
                    full_path = os.path.join(root, file)
                    rel_path = os.path.relpath(full_path, temp_dir)

                    try:
                        with open(full_path, "r", encoding="utf-8", errors="ignore") as f:
                            existing_files[rel_path] = f.read()
                    except Exception as e:
                        print(f"[read_existing_repo_files] Could not read {rel_path}: {e}")

        print(f"[read_existing_repo_files] Read {len(existing_files)} files from repo")

    finally:
        shutil.rmtree(temp_dir, ignore_errors=True)

    return existing_files


# -----------------------------------------
# Metadata Injection
# -----------------------------------------

def inject_metadata(content: str, ticket_id: str, branch: str) -> str:
    header = f"""# ---------------------------------------
# Generated by SDLC Engine
# Ticket: {ticket_id}
# Branch: {branch}
# Generated At: {datetime.datetime.utcnow().isoformat()}Z
# ---------------------------------------

"""
    return header + content


# -----------------------------------------
# Main Sprint Executor
# -----------------------------------------

def execute_sprint(data: SprintExecutionRequest):

    generated_files = []
    repo_snapshot = []
    data_models = {}
    ast_report_saved = False  # only save AST report once

    manifest = {
        "branch": data.branch_name,
        "generated_at": datetime.datetime.utcnow().isoformat() + "Z",
        "mode": data.mode,
        "artifacts": []
    }

    # =========================================
    # READ EXISTING REPO FILES FOR AST CONTEXT
    # =========================================
    existing_file_contents = {}

    if data.mode == "update":
        print(f"[execute_sprint] UPDATE mode — reading existing repo for AST context")
        try:
            existing_file_contents = read_existing_repo_files(
                data.repo_url,
                data.branch_name
            )
            repo_snapshot = list(existing_file_contents.keys())
            print(f"[execute_sprint] {len(repo_snapshot)} existing files loaded into context")

        except Exception as e:
            print(f"[execute_sprint] Could not read existing repo: {e} — continuing without AST context")

    # =========================================
    # PROCESS EACH TICKET
    # =========================================
    for ticket in data.tickets:

        preview = generate_file_for_ticket(
            ticket=ticket,
            architecture=data.architecture,
            data_models=data_models,
            repo_tree=repo_snapshot,
            generated_files=generated_files,
            existing_file_contents=existing_file_contents
        )

        # Safety check
        if not isinstance(preview, dict) or "file_path" not in preview:
            print(f"[execute_sprint] Skipping ticket — invalid LLM response: {preview}")
            continue

        file_path = preview["file_path"]
        original_content = preview["content"]

        # Save AST report as committed file — only once per sprint
        if not ast_report_saved and preview.get("ast_report"):
            ast_report = preview["ast_report"]
            generated_files.append({
                "file_path": "sdlc_ast_report.json",
                "content": json.dumps(ast_report, indent=2)
            })
            ast_report_saved = True
            print(f"[execute_sprint] AST report saved — analyzed {ast_report['total_files_read']} files")

        # =========================
        # BOOTSTRAP MODE
        # =========================
        if data.mode == "bootstrap":
            if file_exists_in_repo(data.repo_url, data.branch_name, file_path):
                print(f"[bootstrap] Skipping {file_path} — already exists.")
                continue

        # =========================
        # PREVIEW MODE
        # =========================
        if data.mode == "preview":
            return {
                "status": "PREVIEW_READY",
                "file_path": file_path,
                "content_hash": hash(original_content),
                "ast_files_loaded": len(existing_file_contents)
            }

        # =========================
        # UPDATE MODE
        # =========================
        content_with_metadata = inject_metadata(
            original_content,
            ticket.get("id", "UNKNOWN"),
            data.branch_name
        )

        generated_files.append({
            "file_path": file_path,
            "content": content_with_metadata
        })

        if file_path not in repo_snapshot:
            repo_snapshot.append(file_path)

        manifest["artifacts"].append({
            "ticket_id": ticket.get("id", "UNKNOWN"),
            "file_path": file_path,
            "acceptance_criteria": ticket.get("acceptance_criteria", []),
            "generated_at": datetime.datetime.utcnow().isoformat() + "Z"
        })

    # =========================================
    # NOTHING GENERATED
    # =========================================
    if not generated_files:
        return {
            "status": "NO_CHANGES",
            "tickets_processed": len(data.tickets),
            "files_generated": 0,
            "git_status": "SKIPPED_ALL_EXISTING",
            "ast_files_loaded": len(existing_file_contents)
        }

    # Add manifest
    generated_files.append({
        "file_path": "sdlc_manifest.json",
        "content": json.dumps(manifest, indent=2)
    })

    # =========================================
    # PUSH TO GIT
    # =========================================
    push_response = push_files_to_repo(
        repo_url=data.repo_url,
        branch_name=data.branch_name,
        files=generated_files,
        commit_message=f"Sprint execution ({data.mode}) auto-commit"
    )

    return {
        "status": "SPRINT_EXECUTED",
        "mode": data.mode,
        "tickets_processed": len(data.tickets),
        "files_generated": len(generated_files),
        "ast_files_loaded": len(existing_file_contents),
        "git_status": push_response
    }